# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


  use_frameworks!

  target 'homework6' do
# Comment the next line if you don't want to use dynamic frameworks
  




# Pods for homework6
  pod 'Alamofire'
  pod  'SwiftyJSON'
  pod  'SwiftSpinner'
  pod 'PromiseKit'
end
